project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "portfolio/**/*.qmd"
  resources:
    - CNAME
    - "*.pdf"
    - "*.png"
    - "portfolio/csr/references.bib"

website:
  title: "Robert J. Carroll"
  favicon: thumbnail.png
  navbar:
    background: light
    foreground: dark
    left:
      - text: "Robert J. Carroll"
        href: index.qmd
    right:
      - text: "CV"
        href: CV.pdf
      - icon: github
        href: https://github.com/rjcarroll
      - icon: linkedin
        href: https://www.linkedin.com/in/robcarrolluiuc/
      - text: "Scholar"
        href: https://scholar.google.com/citations?user=mzFx-RIAAAAJ&hl=en
  page-footer:
    left: "Robert J. Carroll"
    right: "University of Illinois at Urbana-Champaign"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true
