<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robert J. Carroll">

<title>D-SOCIAL-KLD: Methodology – Robert J. Carroll</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../thumbnail.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3db3234f3da9adc8360dc180646296bd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Robert J. Carroll</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../notes.html"> 
<span class="menu-text">Grad Notes</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://calendly.com/robcarroll"> <i class="bi bi-calendar" role="img">
</i> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../CV.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:rjc@illinois.edu"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rjcarroll"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/robcarrolluiuc/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://scholar.google.com/citations?user=mzFx-RIAAAAJ&amp;hl=en"> 
<span class="menu-text">Scholar</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-measurement-problem" id="toc-the-measurement-problem" class="nav-link active" data-scroll-target="#the-measurement-problem"><span class="header-section-number">1</span> The measurement problem</a></li>
  <li><a href="#model-specification" id="toc-model-specification" class="nav-link" data-scroll-target="#model-specification"><span class="header-section-number">2</span> Model specification</a>
  <ul class="collapse">
  <li><a href="#sec-model" id="toc-sec-model" class="nav-link" data-scroll-target="#sec-model"><span class="header-section-number">2.1</span> The two-parameter probit IRT model</a></li>
  <li><a href="#sec-dynamic" id="toc-sec-dynamic" class="nav-link" data-scroll-target="#sec-dynamic"><span class="header-section-number">2.2</span> Dynamic prior on <span class="math inline">\(\theta\)</span></a></li>
  <li><a href="#item-priors" id="toc-item-priors" class="nav-link" data-scroll-target="#item-priors"><span class="header-section-number">2.3</span> Item priors</a></li>
  </ul></li>
  <li><a href="#sec-identification" id="toc-sec-identification" class="nav-link" data-scroll-target="#sec-identification"><span class="header-section-number">3</span> Identification</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">4</span> Estimation</a>
  <ul class="collapse">
  <li><a href="#from-gibbs-to-hmc" id="toc-from-gibbs-to-hmc" class="nav-link" data-scroll-target="#from-gibbs-to-hmc"><span class="header-section-number">4.1</span> From Gibbs to HMC</a></li>
  <li><a href="#implementation-details" id="toc-implementation-details" class="nav-link" data-scroll-target="#implementation-details"><span class="header-section-number">4.2</span> Implementation details</a></li>
  <li><a href="#estimation-results" id="toc-estimation-results" class="nav-link" data-scroll-target="#estimation-results"><span class="header-section-number">4.3</span> Estimation results</a></li>
  </ul></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings"><span class="header-section-number">5</span> Key findings</a>
  <ul class="collapse">
  <li><a href="#the-model-works-at-scale" id="toc-the-model-works-at-scale" class="nav-link" data-scroll-target="#the-model-works-at-scale"><span class="header-section-number">5.1</span> The model works at scale</a></li>
  <li><a href="#csr-improved-broadly-over-19912018" id="toc-csr-improved-broadly-over-19912018" class="nav-link" data-scroll-target="#csr-improved-broadly-over-19912018"><span class="header-section-number">5.2</span> CSR improved broadly over 1991–2018</a></li>
  <li><a href="#indicator-informativeness-varies-substantially" id="toc-indicator-informativeness-varies-substantially" class="nav-link" data-scroll-target="#indicator-informativeness-varies-substantially"><span class="header-section-number">5.3</span> Indicator informativeness varies substantially</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">6</span> Data</a>
  <ul class="collapse">
  <li><a href="#source" id="toc-source" class="nav-link" data-scroll-target="#source"><span class="header-section-number">6.1</span> Source</a></li>
  <li><a href="#preprocessing" id="toc-preprocessing" class="nav-link" data-scroll-target="#preprocessing"><span class="header-section-number">6.2</span> Preprocessing</a></li>
  <li><a href="#scale-and-sparsity" id="toc-scale-and-sparsity" class="nav-link" data-scroll-target="#scale-and-sparsity"><span class="header-section-number">6.3</span> Scale and sparsity</a></li>
  </ul></li>
  <li><a href="#interpreting-the-output" id="toc-interpreting-the-output" class="nav-link" data-scroll-target="#interpreting-the-output"><span class="header-section-number">7</span> Interpreting the output</a>
  <ul class="collapse">
  <li><a href="#scores-theta" id="toc-scores-theta" class="nav-link" data-scroll-target="#scores-theta"><span class="header-section-number">7.1</span> Scores (<span class="math inline">\(\theta\)</span>)</a></li>
  <li><a href="#item-parameters-alpha-beta" id="toc-item-parameters-alpha-beta" class="nav-link" data-scroll-target="#item-parameters-alpha-beta"><span class="header-section-number">7.2</span> Item parameters (<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>)</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">D-SOCIAL-KLD: Methodology</h1>
<p class="subtitle lead">Dynamic IRT measurement of corporate social responsibility</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Robert J. Carroll </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="the-measurement-problem" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-measurement-problem"><span class="header-section-number">1</span> The measurement problem</h2>
<p>Corporate social responsibility (CSR) is a latent construct. We do not observe a firm’s CSR directly; instead, we observe dozens of binary indicators—strengths and concerns—coded by ratings agencies like KLD (now MSCI ESG). The question is how to aggregate these indicators into a single score.</p>
<p>The standard approach in the management literature is the <strong>KLD Index</strong>: sum the strengths, subtract the concerns. This treats every indicator as equally informative, which is a strong and often implausible assumption. A strength that virtually every firm earns (e.g., a basic governance policy) tells us much less than one that only the most responsible firms achieve. An additive index cannot distinguish between these cases.</p>
<p><strong>Item response theory</strong> (IRT) offers a principled alternative. Originally developed in psychometrics to score examinees on standardized tests, IRT models the probability of a binary response as a function of the respondent’s latent trait and the item’s statistical properties. The analogy is direct: firms are examinees, KLD indicators are test items, and the latent trait is CSR.</p>
<p>This document describes the dynamic IRT model used to produce D-SOCIAL-KLD scores, covering the model specification, identification strategy, estimation, and key implementation decisions. The original measure was introduced in <span class="citation" data-cites="carroll2016irt">Carroll et al. (<a href="#ref-carroll2016irt" role="doc-biblioref">2016</a>)</span>; this implementation extends coverage through 2018 and re-estimates the model using Stan’s Hamiltonian Monte Carlo sampler.</p>
</section>
<section id="model-specification" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="model-specification"><span class="header-section-number">2</span> Model specification</h2>
<section id="sec-model" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="sec-model"><span class="header-section-number">2.1</span> The two-parameter probit IRT model</h3>
<p>For each observed triple of firm <span class="math inline">\(i\)</span>, KLD indicator <span class="math inline">\(j\)</span>, and year <span class="math inline">\(t\)</span>, the model specifies:</p>
<p><span id="eq-likelihood"><span class="math display">\[
y_{ijt} \sim \text{Bernoulli}\bigl(\Phi(\beta_{jt} \cdot \theta_{it} - \alpha_{jt})\bigr)
\tag{1}\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\theta_{it}\)</span> is the <strong>latent CSR score</strong> for firm <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>—the quantity of interest.</li>
<li><span class="math inline">\(\alpha_{jt}\)</span> is the <strong>difficulty</strong> of indicator <span class="math inline">\(j\)</span> in year <span class="math inline">\(t\)</span>: how much underlying CSR a firm needs to have a 50% probability of being coded 1 on this indicator, all else equal. Higher <span class="math inline">\(\alpha\)</span> means fewer firms are coded 1 (the indicator is “harder” to earn or harder to avoid).</li>
<li><span class="math inline">\(\beta_{jt}\)</span> is the <strong>discrimination</strong> of indicator <span class="math inline">\(j\)</span> in year <span class="math inline">\(t\)</span>: how steeply the probability of a 1 changes as <span class="math inline">\(\theta\)</span> increases. Strength indicators tend to have <span class="math inline">\(\beta &gt; 0\)</span> (more-responsible firms are more likely to earn the strength). Concern indicators tend to have <span class="math inline">\(\beta &lt; 0\)</span> (more-responsible firms are less likely to have the concern).</li>
<li><span class="math inline">\(\Phi(\cdot)\)</span> is the standard normal CDF (probit link).</li>
</ul>
<p>The discrimination parameter <span class="math inline">\(\beta\)</span> is what makes IRT superior to an additive index. An indicator with <span class="math inline">\(|\beta| \approx 0\)</span> contributes almost nothing to the score; one with large <span class="math inline">\(|\beta|\)</span> is highly informative. The model estimates these weights from the data rather than assuming they are equal.</p>
</section>
<section id="sec-dynamic" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="sec-dynamic"><span class="header-section-number">2.2</span> Dynamic prior on <span class="math inline">\(\theta\)</span></h3>
<p>A static IRT model would treat each year as an independent cross-section, discarding the information that a firm rated highly in 2005 is likely to be rated highly in 2006. The <strong>dynamic</strong> extension imposes a random-walk prior on <span class="math inline">\(\theta\)</span>:</p>
<p><span id="eq-init"><span class="math display">\[
\theta_{i, t_0} \sim \text{Normal}(0, \sigma_{\text{init}})
\tag{2}\]</span></span></p>
<p><span id="eq-transition"><span class="math display">\[
\theta_{i,t} \mid \theta_{i,t-1} \sim \text{Normal}(\theta_{i,t-1}, \sigma_{\text{firm},i})
\tag{3}\]</span></span></p>
<p>The firm-specific innovation standard deviation <span class="math inline">\(\sigma_{\text{firm},i}\)</span> governs how quickly each firm’s CSR position can change year to year. A firm with small <span class="math inline">\(\sigma_{\text{firm}}\)</span> has a CSR trajectory that is relatively stable; a firm with large <span class="math inline">\(\sigma_{\text{firm}}\)</span> can shift rapidly.</p>
<p>Rather than estimating each <span class="math inline">\(\sigma_{\text{firm},i}\)</span> in isolation, we use <strong>partial pooling</strong> via a hierarchical prior:</p>
<p><span class="math display">\[
\sigma_{\text{firm},i} \sim \text{Half-Normal}(0, \sigma_{\text{global}})
\]</span></p>
<p><span class="math display">\[
\sigma_{\text{global}} \sim \text{Half-Normal}(0, 1)
\]</span></p>
<p>This structure lets the model learn from the full cross-section of firms what a “typical” rate of change looks like, while still allowing individual firms to deviate from that baseline. The result is a Bayesian shrinkage estimator: firms with limited data are pulled toward the group mean rate of change, while firms with abundant data are estimated more freely.</p>
</section>
<section id="item-priors" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="item-priors"><span class="header-section-number">2.3</span> Item priors</h3>
<p>The difficulty and discrimination parameters receive mildly regularizing priors:</p>
<p><span class="math display">\[
\alpha_{jt} \sim \text{Normal}(0, 5) \qquad \beta_{jt} \sim \text{Normal}(0, 2.5)
\]</span></p>
<p>These are wide enough to let the data drive the estimates while preventing extreme values that could destabilize the sampler.</p>
</section>
</section>
<section id="sec-identification" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-identification"><span class="header-section-number">3</span> Identification</h2>
<p>IRT models are identified only up to a <strong>reflection</strong> (multiplying all <span class="math inline">\(\theta\)</span> by <span class="math inline">\(-1\)</span> and all <span class="math inline">\(\beta\)</span> by <span class="math inline">\(-1\)</span> gives the same likelihood) and a <strong>scale</strong> (the units of <span class="math inline">\(\theta\)</span> are arbitrary without a reference point).</p>
<p>We fix both by <strong>pinning</strong> two anchor firms’ first-year scores to fixed values:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Anchor</th>
<th>Constraint</th>
<th>Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Halliburton (HAL)</td>
<td><span class="math inline">\(\theta_{\text{HAL},t_0} = -1\)</span></td>
<td>Consistently associated with environmental and governance controversies; used as the negative anchor in <span class="citation" data-cites="carroll2016irt">Carroll et al. (<a href="#ref-carroll2016irt" role="doc-biblioref">2016</a>)</span></td>
</tr>
<tr class="even">
<td>Abbott Laboratories (ABT)</td>
<td><span class="math inline">\(\theta_{\text{ABT},t_0} = +1\)</span></td>
<td>Consistently ranked among top corporate citizens in major CSR indices (DJSI, MSCI, Fortune)</td>
</tr>
</tbody>
</table>
<p>where <span class="math inline">\(t_0\)</span> denotes each anchor firm’s first appearance in the data. The fixed values apply only to the first-year score; subsequent years evolve freely under the dynamic prior. Fixing at <span class="math inline">\(\pm 1\)</span> rather than merely constraining the sign eliminates a scale degeneracy: sign constraints allow the anchor scores to hover near zero, leaving the overall scale of <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\beta\)</span> unidentified across chains. The fixed values are hard-coded in the <code>transformed parameters</code> block; the anchor scores are not sampled parameters.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The original paper used Microsoft (MSFT) as the positive anchor. MSFT lacks KLD indicator data before 2010, making it unsuitable for the full panel. Johnson &amp; Johnson (JNJ) was considered as a replacement but also lacks data before 2001. ABT has complete coverage and a strong, well-documented CSR record throughout the period.</p>
</div>
</div>
</section>
<section id="estimation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="estimation"><span class="header-section-number">4</span> Estimation</h2>
<section id="from-gibbs-to-hmc" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="from-gibbs-to-hmc"><span class="header-section-number">4.1</span> From Gibbs to HMC</h3>
<p>The original D-SOCIAL-KLD scores were estimated using <code>MCMCpack::MCMCdynamicIRT1d</code> in R, which implements a Gibbs sampler with data augmentation following <span class="citation" data-cites="martin2002dynamic">Martin and Quinn (<a href="#ref-martin2002dynamic" role="doc-biblioref">2002</a>)</span>. Gibbs sampling has several limitations for a model of this size:</p>
<ol type="1">
<li><strong>High autocorrelation</strong>: Gibbs draws are serially correlated because each parameter is updated conditional on all others. Effective sample sizes are often a small fraction of the nominal chain length.</li>
<li><strong>No built-in diagnostics</strong>: convergence must be assessed post hoc, typically by informal visual inspection of trace plots.</li>
<li><strong>Difficult to parallelize</strong>: Gibbs updates are inherently sequential; running multiple chains requires separate processes with no communication.</li>
</ol>
<p>This implementation uses <strong>Stan</strong> <span class="citation" data-cites="carpenter2017stan">(<a href="#ref-carpenter2017stan" role="doc-biblioref">Carpenter et al. 2017</a>)</span>, which employs the No-U-Turn Sampler (NUTS), an adaptive variant of Hamiltonian Monte Carlo (HMC) <span class="citation" data-cites="hoffman2014nuts">(<a href="#ref-hoffman2014nuts" role="doc-biblioref">Hoffman and Gelman 2014</a>)</span>. HMC uses gradient information to make large, low-autocorrelation moves through the posterior, resulting in dramatically higher effective sample sizes per draw. Stan also provides:</p>
<ul>
<li><strong>Automatic diagnostics</strong>: divergent transitions, R-hat, bulk and tail effective sample size</li>
<li><strong>Parallel chains</strong>: multiple chains run simultaneously, enabling both faster estimation and formal convergence assessment</li>
<li><strong>Pointwise log-likelihood</strong>: can be computed in a <code>generated quantities</code> block for leave-one-out cross-validation via the <code>loo</code> package <span class="citation" data-cites="vehtari2017loo">(<a href="#ref-vehtari2017loo" role="doc-biblioref">Vehtari et al. 2017</a>)</span>. This block is omitted from the primary model file because storing an <span class="math inline">\(N\)</span>-length vector per posterior draw exhausts memory for the full KLD dataset (~3.3M observations). LOO diagnostics should be computed on a subsample or via moment matching.</li>
</ul>
</section>
<section id="implementation-details" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="implementation-details"><span class="header-section-number">4.2</span> Implementation details</h3>
<p>The Stan model uses several techniques to handle the scale of the problem:</p>
<p><strong>Sparse data representation.</strong> The KLD panel is highly sparse: firms enter and exit the database, and the set of indicators changes over time. Rather than passing the full firm <span class="math inline">\(\times\)</span> indicator <span class="math inline">\(\times\)</span> year array to Stan (which would be mostly NA), the R preprocessing scripts convert the data to a flat list of non-missing <span class="math inline">\((i, j, t, y)\)</span> tuples. This reduces the data footprint from millions of potential cells to the 3,273,013 actually observed.</p>
<p><strong>Non-centered parameterization (NCP).</strong> The centered form of the dynamic prior creates a funnel geometry in the joint posterior: when <span class="math inline">\(\sigma_{\text{global}}\)</span> is small, <span class="math inline">\(\sigma_{\text{firm}}\)</span> must be small, and when <span class="math inline">\(\sigma_{\text{firm}}\)</span> is small, consecutive <span class="math inline">\(\theta\)</span> values must be nearly identical. HMC must take extremely small leapfrog steps to navigate this narrow funnel, resulting in nearly all transitions hitting the maximum treedepth and near-zero E-BFMI values.</p>
<p>The NCP decouples these hierarchical dependencies by introducing raw standard-normal innovation parameters and treating <span class="math inline">\(\theta\)</span> as a deterministic function in <code>transformed parameters</code>:</p>
<p><span class="math display">\[
\sigma_{\text{firm},i} = \sigma_{\text{global}} \cdot \tilde{\sigma}_i, \qquad \tilde{\sigma}_i \sim \text{Half-Normal}(0,1)
\]</span></p>
<p><span class="math display">\[
\theta_{i,t_0} = \sigma_{\text{init}} \cdot z^{\text{init}}_i, \qquad z^{\text{init}}_i \sim \text{Normal}(0,1)
\]</span></p>
<p><span class="math display">\[
\theta_{i,t} = \theta_{i,t-1} + \sigma_{\text{firm},i} \cdot z^{\text{trans}}_{i,t}, \qquad z^{\text{trans}}_{i,t} \sim \text{Normal}(0,1)
\]</span></p>
<p>(with the exception of the anchor firms’ first-year scores, which are fixed constants—not sampled—as described in <a href="#sec-identification" class="quarto-xref">Section&nbsp;3</a>). The <span class="math inline">\(\theta\)</span> vector is assembled sequentially in the <code>transformed parameters</code> block by processing transitions in chronological order within each firm. Firm-years that follow gaps in the panel (i.e., years that are not consecutive transitions) receive the same <span class="math inline">\(\sigma_{\text{init}} \cdot z\)</span> initialization as first appearances.</p>
<p><strong>Initialization.</strong> All chains are initialized at zero on the unconstrained scale (<code>init = 0</code>). Under NCP, this places all <span class="math inline">\(z\)</span> innovations at zero, so every non-anchor <span class="math inline">\(\theta\)</span> starts at zero; the anchor scores are fixed at <span class="math inline">\(\pm 1\)</span> and are not sampled. This avoids the initialization failures that arise with random starts when the dynamic prior drives <span class="math inline">\(\log p\)</span> to <span class="math inline">\(-\infty\)</span>.</p>
<p><strong>Post-estimation memory management.</strong> The full model has approximately 120,000 parameters, producing chain CSVs of ~3.4 GB each (13.6 GB total for 4 chains). Neither <code>cmdstanr::as_cmdstan_fit()</code> nor <code>data.table::fread()</code> can load these files on a 16 GB machine—the former exhausts memory building its internal data structure, and the latter overflows its header-line parser on the ~1.3 MB, 120,000-field column header. The pipeline converts the raw chain CSVs to <strong>Apache Parquet</strong> via Arrow, dropping the NCP internal parameters (<code>z_init</code>, <code>z_trans</code>, <code>sigma_firm_raw</code>) that are never needed downstream. This cuts the column count from ~120,000 to ~62,000 and file size to ~1.5 GB per chain. Diagnostics and score extraction then use Arrow’s column-selective Parquet reads, loading only the parameters needed for each operation—typically a few hundred to a few thousand columns at a time, keeping peak memory well under 1 GB.</p>
</section>
<section id="estimation-results" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="estimation-results"><span class="header-section-number">4.3</span> Estimation results</h3>
<p>The model was estimated with 4 chains, each running 1,000 warmup iterations and 2,500 sampling iterations (10,000 posterior draws total), with <code>adapt_delta = 0.9</code>. Wall-clock time was approximately 3.2 days on an Apple M-series machine (single-threaded per chain, 4 chains in parallel).</p>
<section id="sampler-diagnostics" class="level4" data-number="4.3.1">
<h4 data-number="4.3.1" class="anchored" data-anchor-id="sampler-diagnostics"><span class="header-section-number">4.3.1</span> Sampler diagnostics</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Diagnostic</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Divergences</td>
<td>0 across all 4 chains</td>
</tr>
<tr class="even">
<td>Max treedepth hits</td>
<td>0 (max depth = 10)</td>
</tr>
<tr class="odd">
<td>E-BFMI</td>
<td>0.80, 0.78, 0.76, 0.81</td>
</tr>
</tbody>
</table>
<p>All E-BFMI values are well above the 0.3 concern threshold, confirming that the non-centered parameterization successfully resolves the funnel geometry that plagues the centered form of this model.</p>
</section>
<section id="convergence" class="level4" data-number="4.3.2">
<h4 data-number="4.3.2" class="anchored" data-anchor-id="convergence"><span class="header-section-number">4.3.2</span> Convergence</h4>
<p>Convergence was assessed via R-hat and effective sample size (ESS) on a stratified sample of 352 parameters spanning all parameter types—hyperparameters, item difficulties, item discriminations, firm-year scores, and firm-level innovation standard deviations:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R-hat</td>
<td>Max 1.004 across all 352 parameters (all <span class="math inline">\(\leq\)</span> 1.01)</td>
</tr>
<tr class="even">
<td>Bulk ESS</td>
<td>Min 741 (<code>sigma_init</code>), generally 2,000–26,000+</td>
</tr>
<tr class="odd">
<td>Tail ESS</td>
<td>Min 1,263, generally 2,800–10,000+</td>
</tr>
</tbody>
</table>
<p>The lowest bulk ESS belongs to <span class="math inline">\(\sigma_{\text{init}}\)</span>, the global initialization scale—a single scalar governing all firms’ first-year draws. Even at 741, this represents adequate posterior exploration for a parameter with a simple unimodal marginal. All item parameters and firm-year scores have bulk ESS comfortably in the thousands.</p>
</section>
<section id="sec-anchors" class="level4" data-number="4.3.3">
<h4 data-number="4.3.3" class="anchored" data-anchor-id="sec-anchors"><span class="header-section-number">4.3.3</span> Anchor trajectories</h4>
<p>The identification strategy pins each anchor firm’s first-year score to a fixed value (HAL at <span class="math inline">\(-1\)</span>, ABT at <span class="math inline">\(+1\)</span> in 1991); subsequent years evolve freely under the dynamic prior. The resulting trajectories are substantively revealing.</p>
<p><strong>ABT</strong> (the positive anchor) remains consistently positive throughout the panel, with posterior means ranging from 0.65 to 0.87—stable high-CSR performance over nearly three decades.</p>
<p><strong>HAL</strong> (the negative anchor) tells a more surprising story. Pinned at <span class="math inline">\(-1\)</span> in 1991, Halliburton’s estimated CSR score turns positive by 1993 and remains in the 0.5–0.8 range for the remainder of the period. This is not a failure of identification—the first-year pin successfully sets the scale, and the model is free to let the trajectory evolve as the data dictate. What the data dictate is that even a firm selected as a low-CSR exemplar in the early 1990s improved substantially over the following decades.</p>
<p>This pattern is not unique to Halliburton. Among all firms in the panel with at least 10 years of coverage, not a single one maintains a consistently negative CSR trajectory across the full 1991–2018 period. The most persistently negative firms (e.g., Saul Centers, DXP Enterprises, Cass Financial) enter the panel in 2003 or later, after KLD expanded its coverage universe to include smaller firms. The implication is clear: corporate social responsibility, as measured by KLD indicators, improved broadly and substantially over this period. A dynamic model captures this secular trend through the <span class="math inline">\(\theta\)</span> trajectories; a static cross-sectional analysis would miss it entirely.</p>
</section>
</section>
</section>
<section id="key-findings" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="key-findings"><span class="header-section-number">5</span> Key findings</h2>
<p>Three results from the estimation merit emphasis.</p>
<section id="the-model-works-at-scale" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="the-model-works-at-scale"><span class="header-section-number">5.1</span> The model works at scale</h3>
<p>Zero divergences, zero max-treedepth hits, healthy E-BFMI, and R-hat <span class="math inline">\(\leq\)</span> 1.004 across all spot-checked parameters. The non-centered parameterization eliminates the pathological funnel geometry that would otherwise cripple HMC at this scale. This is a model with over 120,000 parameters estimated from 3.3 million observations; clean diagnostics validate both the parameterization strategy and the choice of Stan over Gibbs sampling.</p>
</section>
<section id="csr-improved-broadly-over-19912018" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="csr-improved-broadly-over-19912018"><span class="header-section-number">5.2</span> CSR improved broadly over 1991–2018</h3>
<p>The anchor trajectory analysis (see <a href="#sec-anchors" class="quarto-xref">Section&nbsp;4.3.3</a>) reveals that no firm with full-panel coverage maintains a persistently negative CSR score. Halliburton—chosen as a low-CSR exemplar based on its environmental and governance record—turns positive within two years of the 1991 starting point. This reflects the observable pattern that KLD strength indicators became more widely adopted and concern indicators became less prevalent over time. The dynamic model captures this secular improvement through the firm-year <span class="math inline">\(\theta\)</span> trajectories rather than absorbing it into the item parameters, making the trend visible and measurable.</p>
</section>
<section id="indicator-informativeness-varies-substantially" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="indicator-informativeness-varies-substantially"><span class="header-section-number">5.3</span> Indicator informativeness varies substantially</h3>
<p>The estimated discrimination parameters (<span class="math inline">\(\beta\)</span>) range widely across indicators. Some KLD items sharply separate high- from low-CSR firms; others contribute almost no discriminating power. This variation is precisely what the additive KLD Index cannot capture. By weighting all indicators equally, the index treats a near-universal governance checkbox the same as a rare environmental commitment that only the most responsible firms achieve. The IRT scores correct for this by data-adaptively downweighting uninformative items and amplifying informative ones.</p>
</section>
</section>
<section id="data" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="data"><span class="header-section-number">6</span> Data</h2>
<section id="source" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="source"><span class="header-section-number">6.1</span> Source</h3>
<p>The raw data come from KLD STATS (now MSCI ESG), a panel of binary CSR indicators for publicly traded U.S. firms. The dataset used here covers <strong>1991–2018</strong> and is available through Wharton Research Data Services (WRDS). KLD indicators are organized into categories (community, diversity, employee relations, environment, human rights, product) and coded as either strengths or concerns.</p>
</section>
<section id="preprocessing" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="preprocessing"><span class="header-section-number">6.2</span> Preprocessing</h3>
<p>The cleaning pipeline handles several data-quality issues:</p>
<ol type="1">
<li><strong>Non-binary values</strong>: a small number of indicator values exceed 1 (e.g., <code>HUM_str_num = 2</code>). These are clamped to 1.</li>
<li><strong>Ticker disambiguation</strong>: KLD’s coverage expanded over time, and different firms occasionally share the same ticker symbol across coverage universes. The disambiguation uses <code>issuerid</code> where available (2017–2018) and deterministic numeric suffixes (<code>.2</code>, <code>.3</code>, …) for earlier years.</li>
<li><strong>Time-varying indicator sets</strong>: not all indicators appear in all years. Columns that are entirely NA in a given year are excluded from that year’s item set.</li>
<li><strong>Universe restriction</strong>: the estimation sample is restricted to firms present in the KLD database by 2012, ensuring comparability with the original published scores.</li>
</ol>
</section>
<section id="scale-and-sparsity" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="scale-and-sparsity"><span class="header-section-number">6.3</span> Scale and sparsity</h3>
<p>The full panel contains 6,324 unique firms, 2,068 indicator-year items, and 3,273,013 non-missing observations across 51,586 firm-years. Coverage is uneven: the early KLD years (1991–2000) include ~650 firms per year; later years include 3,000+. Many prominent firms (e.g., IBM, Coca-Cola) have surprisingly sparse indicator data in certain periods, reflecting KLD’s evolving coverage universe rather than missing observations in the usual sense.</p>
</section>
</section>
<section id="interpreting-the-output" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="interpreting-the-output"><span class="header-section-number">7</span> Interpreting the output</h2>
<section id="scores-theta" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="scores-theta"><span class="header-section-number">7.1</span> Scores (<span class="math inline">\(\theta\)</span>)</h3>
<p>The primary output is a posterior distribution over <span class="math inline">\(\theta_{it}\)</span> for each firm-year. The scores file reports the posterior mean, standard deviation, and percentiles.</p>
<p>Key properties:</p>
<ul>
<li><strong>Centered near zero</strong>: by construction, the distribution of scores in any given year has mean near zero. Positive scores indicate above-median CSR; negative scores indicate below-median.</li>
<li><strong>Interval-scaled</strong>: differences between scores are meaningful (a firm at +1.5 has measurably higher CSR than a firm at +0.5), but ratios are not (a score of +2 does not mean “twice as responsible” as +1).</li>
<li><strong>Uncertainty quantified</strong>: the posterior SD for each firm-year is an explicit measure of estimation uncertainty. Firms with more indicators observed in a given year will have smaller SDs (more precise scores). Researchers should propagate this uncertainty into downstream analyses.</li>
</ul>
</section>
<section id="item-parameters-alpha-beta" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="item-parameters-alpha-beta"><span class="header-section-number">7.2</span> Item parameters (<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>)</h3>
<p>Posterior summaries for each indicator’s difficulty and discrimination are also available. These are useful for understanding which KLD indicators are most informative about the latent CSR dimension and how the indicator set has evolved over time.</p>
</section>
</section>
<section id="references" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="references"><span class="header-section-number">8</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-carpenter2017stan" class="csl-entry" role="listitem">
Carpenter, Bob, Andrew Gelman, Matthew D. Hoffman, et al. 2017. <span>“Stan: A Probabilistic Programming Language.”</span> <em>Journal of Statistical Software</em> 76 (1): 1–32. <a href="https://doi.org/10.18637/jss.v076.i01">https://doi.org/10.18637/jss.v076.i01</a>.
</div>
<div id="ref-carroll2016irt" class="csl-entry" role="listitem">
Carroll, Robert J., David M. Primo, and Brian K. Richter. 2016. <span>“Using Item Response Theory to Improve Measurement in Strategic Management Research: <span>An</span> Application to Corporate Social Responsibility.”</span> <em>Strategic Management Journal</em> 37 (1): 66–85. <a href="https://doi.org/10.1002/smj.2463">https://doi.org/10.1002/smj.2463</a>.
</div>
<div id="ref-hoffman2014nuts" class="csl-entry" role="listitem">
Hoffman, Matthew D., and Andrew Gelman. 2014. <span>“The <span>No-U-Turn</span> Sampler: Adaptively Setting Path Lengths in <span>Hamiltonian</span> <span>Monte</span> <span>Carlo</span>.”</span> <em>Journal of Machine Learning Research</em> 15 (47): 1593–623.
</div>
<div id="ref-martin2002dynamic" class="csl-entry" role="listitem">
Martin, Andrew D., and Kevin M. Quinn. 2002. <span>“Dynamic Ideal Point Estimation via <span>Markov</span> Chain <span>Monte</span> <span>Carlo</span> for the <span>U.S.</span> <span>Supreme</span> <span>Court</span>, 1953–1999.”</span> <em>Political Analysis</em> 10 (2): 134–53. <a href="https://doi.org/10.1093/pan/10.2.134">https://doi.org/10.1093/pan/10.2.134</a>.
</div>
<div id="ref-vehtari2017loo" class="csl-entry" role="listitem">
Vehtari, Aki, Andrew Gelman, and Jonah Gabry. 2017. <span>“Practical <span>Bayesian</span> Model Evaluation Using Leave-One-Out Cross-Validation and <span>WAIC</span>.”</span> <em>Statistics and Computing</em> 27 (5): 1413–32. <a href="https://doi.org/10.1007/s11222-016-9696-4">https://doi.org/10.1007/s11222-016-9696-4</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/robertjcarroll\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Robert J. Carroll</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>University of Illinois at Urbana-Champaign</p>
</div>
  </div>
</footer>




</body></html>